### ISSUE TITLE
Initialization failure

### ISSUE THREAD

**Issue by MomentQYC** [duo/matrix-qq#23]
System: Ubuntu 20.04
Manually compiled (Completes all required .h files)
Synapse 1.81.0 (Install via apt)
The required modules are installed and enabled
```
[Apr 22, 2023 22:51:40] [INFO] Initializing matrix-qq 0.1.6 (Apr 22 2023, 20:38:10 with go1.20.3)
[Apr 22, 2023 22:51:40] [INFO] Bridge initialization complete, starting...
[Apr 22, 2023 22:51:40] [Database/INFO] Database currently on v3, latest: v3
[Apr 22, 2023 22:51:40] [Database/StateStore/INFO] Database currently on v3, latest: v3
[Apr 22, 2023 22:51:41] [ERROR] Failed to connect to homeserver: failed to ensure registered: failed to POST /_matrix/client/v3/register: M_UNKNOWN (HTTP 400): Appservice token must be provided when using a type of m.login.application_service. Retrying in 10 seconds...
```
The endpoint displays 
```json
{"errcode": "M_UNRECOGNIZED", "error": "Unrecognized request"}
```

**Comment by duo** [comment]
检查下 matrix-qq 的 `config.yaml` 配置里的 `appservice.as_token` 有没有值, 以及和 `registration.yaml` 里的是否匹配
感觉是你之前关的 #22 里, 没有正确生成 `registration.yaml`, 导致一些值没自动生成 (比如 as_token, hs_token 等)

**Comment by MomentQYC** [comment]
> 检查下 matrix-qq 的 `config.yaml` 配置里的 `appservice.as_token` 有没有值, 以及和 `registration.yaml` 里的是否匹配
> 
> 感觉是你之前关的 #22 里, 没有正确生成 `registration.yaml`, 导致一些值没自动生成 (比如 as_token, hs_token 等)

没有生成新文件，直接终止了
之前那个是提错地方了

**Comment by duo** [comment]
不清楚你之前的步骤是怎么样的, 但是 matrix-qq 第一次运行的时候会生成 `config.yaml`, 这时候针对自己的情况对这个配置文件进行修改, 然后再执行一次会生成 `registration.yaml`

**Comment by MomentQYC** [comment]
> 不清楚你之前的步骤是怎么样的, 但是 matrix-qq 第一次运行的时候会生成 `config.yaml`, 这时候针对自己的情况对这个配置文件进行修改, 然后再执行一次会生成 `registration.yaml`

有config.yaml，但是再运行就会报那个错，然后就没有然后了
没有生成新文件

**Comment by duo** [comment]
你说的报错信息是指之前 #22 的
```
Exception in thread "main" com.charleskorn.kaml.UnknownPropertyException at bridge.double_puppet_server_map on line 17, column 5: Unknown property 'double_puppet_server_map'. Known properties are: permissions
        at com.charleskorn.kaml.YamlObjectInput.throwUnknownProperty(YamlObjectInput.kt:73)
        at com.charleskorn.kaml.YamlObjectInput.decodeElementIndex(YamlObjectInput.kt:43)
        at land.melty.matrixqqbridge.Config$Bridge$$serializer.deserialize(Config.kt:23)
```
那些么?

**Comment by duo** [comment]
大概明白了, 你是自己编译的, 然后没通过 `docker-run.sh` 那个脚本运行是吧?
那么, 你有 `config.yaml` 的话, 执行 `matrix-qq -g -c config.yaml -r qq-registration.yaml` 来生成 `qq-registration.yaml`
然后照着 https://duo.github.io/posts/matrix-qq-wechat/#matrix-qq 里把 synapse 配好吧

**Comment by MomentQYC** [comment]
> 大概明白了, 你是自己编译的, 然后没通过 `docker-run.sh` 那个脚本运行是吧? 那么, 你有 `config.yaml` 的话, 执行 `matrix-qq -g -c config.yaml -r qq-registration.yaml` 来生成 `qq-registration.yaml` 然后照着 https://duo.github.io/posts/matrix-qq-wechat/#matrix-qq 里把 synapse 配好吧

登录问题解决了，但是发消息没有回复，是必须未加密的私人房间吗？
另外有一个报错
```
pq: duplicate key value violates unique constraint "user_uin_key"
```
pgsql 15.2

**Comment by MomentQYC** [comment]
> > 大概明白了, 你是自己编译的, 然后没通过 `docker-run.sh` 那个脚本运行是吧? 那么, 你有 `config.yaml` 的话, 执行 `matrix-qq -g -c config.yaml -r qq-registration.yaml` 来生成 `qq-registration.yaml` 然后照着 https://duo.github.io/posts/matrix-qq-wechat/#matrix-qq 里把 synapse 配好吧
> 
> 登录问题解决了，但是发消息没有回复，是必须未加密的私人房间吗？ 另外有一个报错
> 
> ```
> pq: duplicate key value violates unique constraint "user_uin_key"
> ```
> 
> pgsql 15.2

发消息的那个问题解决了
但是报错仍然有

**Comment by MomentQYC** [comment]
更新一下现状，新版本不再报错
就是私人房间会有红色感叹号
